import {
  GraphUpArrow,
  Newspaper,
  People,
  Clipboard2Data,
} from "react-bootstrap-icons";

const manifest = [
  {
    appID: "cms_ums",
    appVersion: "1.0.0",
    appName: "Quản lý người dùng",
    appIcon: People,
    appCallToAction: "Người dùng mới",
    appCallToActionHref: "/tao-nguoi-dung-moi",
    appCallToActionRule: "cms_ums/users/2",
    categories: ["NGƯỜI DÙNG", "VAI TRÒ"],
    routes: [
      {
        title: "Tất cả người dùng",
        path: "/tat-ca-nguoi-dung",
        exact: true,
        categories: "NGƯỜI DÙNG",
        rule: "cms_ums/users/1",
      },
      {
        title: "Người dùng nội bộ",
        path: "/nguoi-dung-noi-bo",
        exact: true,
        categories: "NGƯỜI DÙNG",
        rule: "cms_ums/users/1",
      },
      {
        title: "Người dùng thường",
        path: "/nguoi-dung-thuong",
        exact: true,
        categories: "NGƯỜI DÙNG",
        rule: "cms_ums/users/1",
      },
      {
        title: "Yêu cầu xác thực KYC",
        path: "/yeu-cau-xac-thuc-kyc",
        exact: true,
        categories: "NGƯỜI DÙNG",
        rule: "cms_ums/users/1-1",
      },
      // {
      //   title: "Nhân viên bán hàng",
      //   path: "/nhan-vien-ban-hang",
      //   exact: true,
      //   categories: "NGƯỜI DÙNG",
      // },
      {
        title: "Tất cả quyền truy cập",
        path: "/tat-ca-vai-tro",
        exact: true,
        categories: "VAI TRÒ",
        rule: "cms_ums/roles/1",
      },
      {
        title: "Tạo quyền truy cập",
        path: "/tao-quyen-truy-cap",
        exact: true,
        categories: "VAI TRÒ",
        rule: "cms_ums/roles/2",
      },
    ],
  },
  {
    appID: "cms_ams",
    appVersion: "1.0.0",
    appName: "Quản lý tích luỹ",
    appIcon: GraphUpArrow,
    appCallToAction: "Thêm điểm giao dịch",
    appCallToActionHref: "/them-diem-giao-dich",
    appCallToActionRule: "cms_ams/stores/2",
    categories: [
      "GIAO DỊCH",
      "THỐNG KÊ",
      "ĐIỂM GIAO DỊCH",
      "SẢN PHẨM",
      "CÀI ĐẶT",
    ],
    routes: [
      {
        title: "Giao dịch vàng",
        path: "/don-hang",
        exact: true,
        categories: "GIAO DỊCH",
        rule: "cms_ams/orders/1",
      },
      {
        title: "Rút vàng",
        path: "/hen-lay-vang",
        exact: true,
        categories: "GIAO DỊCH",
        rule: "cms_ams/orders/3-2",
      },
      {
        title: "Tất cả giao dịch",
        path: "/tat-ca-giao-dich",
        exact: true,
        categories: "THỐNG KÊ",
        rule: "cms_ams/payment_integrations/1",
      },
      {
        title: "Tất cả điểm giao dịch",
        path: "/tat-ca-diem-giao-dich",
        exact: true,
        categories: "ĐIỂM GIAO DỊCH",
        rule: "cms_ams/stores/1",
      },
      {
        title: "Cài đặt",
        path: "/cai-dat",
        exact: true,
        categories: "CÀI ĐẶT",
        rule: "cms_ams/setting/3",
      },
      {
        title: "Sản phẩm",
        path: "/san-pham",
        exact: true,
        categories: "SẢN PHẨM",
        rule: "cms_ams/setting/3",
      },
    ],
  },
  {
    appID: "cms_blog",
    appVersion: "1.0.0",
    appName: "Quản lý bài viết",
    appIcon: Newspaper,
    appCallToAction: "Tạo bài viết",
    appCallToActionHref: "/tao-bai-viet-moi",
    appCallToActionRule: "cms_blog/blogs/2",
    categories: ["BÀI VIẾT"],
    routes: [
      {
        title: "Bài viết",
        path: "/tat-ca-bai-viet",
        exact: true,
        categories: "BÀI VIẾT",
        rule: "cms_blog/blogs/1",
      },
      // {
      //   title: "Tạo bài viết",
      //   path: "/tao-bai-viet-moi",
      //   exact: true,
      //   categories: "TẠO BÀI VIẾT",
      //   rule: "cms_ams/setting/3",
      // },
    ],
  },
];

export default manifest;
